// components/site/date-picker.tsx
import { useRef } from 'react';
import { format } from 'date-fns';
import { Calendar as CalendarIcon } from 'lucide-react';
import { FieldMetadata, unstable_useControl as useControl } from '@conform-to/react';

import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { cn } from '@/lib/utils';

export function DatePicker({ meta }: { meta: FieldMetadata<Date> }) {
	const triggerRef = useRef<HTMLButtonElement>(null);
	const control = useControl(meta);

	return (
		<div>
			<input
				className="sr-only"
				aria-hidden
				tabIndex={-1}
				ref={control.register}
				name={meta.name}
				defaultValue={meta.initialValue ? new Date(meta.initialValue).toISOString() : ''}
				onFocus={() => {
					triggerRef.current?.focus();
				}}
			/>
			<Popover>
				<PopoverTrigger asChild>
					<Button
						ref={triggerRef}
						variant={'outline'}
						className={cn(
							'w-full justify-start text-left font-normal focus:ring-2 focus:ring-stone-950 focus:ring-offset-2',
							!control.value && 'text-muted-foreground'
						)}
					>
						<CalendarIcon className="mr-2 h-4 w-4" />
						{control.value ? format(control.value, 'PPP') : <span>Pick a date</span>}
					</Button>
				</PopoverTrigger>
				<PopoverContent className="w-auto p-0">
					<Calendar
						mode="single"
						selected={new Date(control.value ?? '')}
						onSelect={(value) => control.change(value?.toISOString() ?? '')}
						initialFocus
					/>
				</PopoverContent>
			</Popover>
		</div>
	);
}

// src/lib/components/site/date-picker.svelte
<script lang="ts">
	import { CalendarIcon } from 'lucide-svelte';
	import { type DateValue, DateFormatter, getLocalTimeZone } from '@internationalized/date';

	import { Button } from '$lib/components/ui/button';
	import { Calendar } from '$lib/components/ui/calendar';
	import * as Popover from '$lib/components/ui/popover';
	import { cn } from '$lib/utils';

	let value: DateValue | undefined;
	export let onChange: (date: string) => void;

	const df = new DateFormatter('en-US', {
		dateStyle: 'long'
	});

	function handleDateChange(v: DateValue | undefined) {
		if (v) onChange(v.toString());
		else onChange('');
	}
</script>

<Popover.Root openFocus>
	<Popover.Trigger asChild let:builder>
		<Button
			variant="outline"
			class={cn(
				'w-[280px] justify-start text-left font-normal',
				!value && 'text-muted-foreground'
			)}
			builders={[builder]}
		>
			<CalendarIcon class="mr-2 size-4" />
			{value ? df.format(value?.toDate(getLocalTimeZone())) : 'Select a Date'}
		</Button>
	</Popover.Trigger>

	<Popover.Content class="w-auto p-0">
		<Calendar bind:value initialFocus onValueChange={handleDateChange} />
	</Popover.Content>
</Popover.Root>
