// components/site/date-picker.tsx
import { useRef } from 'react';
import { format } from 'date-fns';
import { Calendar as CalendarIcon } from 'lucide-react';
import { FieldMetadata, unstable_useControl as useControl } from '@conform-to/react';

import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { cn } from '@/lib/utils';

export function DatePicker({ meta }: { meta: FieldMetadata<Date> }) {
	const triggerRef = useRef<HTMLButtonElement>(null);
	const control = useControl(meta);

	return (
		<div>
			<input
				className="sr-only"
				aria-hidden
				tabIndex={-1}
				ref={control.register}
				name={meta.name}
				defaultValue={meta.initialValue ? new Date(meta.initialValue).toISOString() : ''}
				onFocus={() => {
					triggerRef.current?.focus();
				}}
			/>
			<Popover>
				<PopoverTrigger asChild>
					<Button
						ref={triggerRef}
						variant={'outline'}
						className={cn(
							'w-full justify-start text-left font-normal focus:ring-2 focus:ring-stone-950 focus:ring-offset-2',
							!control.value && 'text-muted-foreground'
						)}
					>
						<CalendarIcon className="mr-2 h-4 w-4" />
						{control.value ? format(control.value, 'PPP') : <span>Pick a date</span>}
					</Button>
				</PopoverTrigger>
				<PopoverContent className="w-auto p-0">
					<Calendar
						mode="single"
						selected={new Date(control.value ?? '')}
						onSelect={(value) => control.change(value?.toISOString() ?? '')}
						initialFocus
					/>
				</PopoverContent>
			</Popover>
		</div>
	);
}

// src/lib/components/ui/date-picker.svelte
<script lang="ts">
	import { CalendarIcon } from 'lucide-svelte';
	import {
		DateFormatter,
		type DateValue,
		getLocalTimeZone,
		today,
		parseDate
	} from '@internationalized/date';

	import { cn } from '$lib/utils';
	import { buttonVariants } from '$lib/components/ui/button';
	import { Calendar } from '$lib/components/ui/calendar';
	import * as Popover from '$lib/components/ui/popover';

	export let date: string | undefined;
	let value: DateValue | undefined;

	const df = new DateFormatter('en-US', {
		dateStyle: 'long'
	});

	$: value = date ? parseDate(date) : undefined;
</script>

<Popover.Root>
	<Popover.Trigger
		class={cn(
			buttonVariants({ variant: 'outline' }),
			'w-[280px] justify-start pl-4 text-left font-normal',
			!value && 'text-muted-foreground'
		)}
	>
		{value ? df.format(value.toDate(getLocalTimeZone())) : 'Pick a date'}
		<CalendarIcon class="ml-auto h-4 w-4 opacity-50" />
	</Popover.Trigger>
	<Popover.Content class="w-auto p-0" side="top">
		<Calendar
			{value}
			minValue={today(getLocalTimeZone())}
			calendarLabel="Date of birth"
			initialFocus
			onValueChange={(v) => {
				if (v) date = v.toString();
				else date = parseDate(today(getLocalTimeZone()).toString()).toString();
			}}
		/>
	</Popover.Content>
</Popover.Root>
