// src/routes/events/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { getFlash } from 'sveltekit-flash-message';
	import type { PageData } from './$types';

	export let data: PageData;
	let isNewEvent = false;

	const flash = getFlash(page);

	$: if ($flash) {
		isNewEvent = true;
	}
</script>

<main class="flex-1 py-12">
	<div class="flex items-center gap-3">
		<hi>Event Details</hi>
		{#if isNewEvent}
			<p class="animate-bounce font-semibold text-green-400">New Event Created!</p>
		{/if}
	</div>
	<p>Event ID: {data.event.id}</p>

	<pre>{JSON.stringify(data.event, null, 2)}</pre>
</main>

// app/events/[id]/page.tsx
import { Metadata } from 'next';
import { cookies } from 'next/headers';

import { getEventById } from '@/lib/models/event';

type PageProps = {
	params: {
		id: string;
	};
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
	const event = await getEventById(params.id);

	return {
		title: event?.name || 'Event Details',
		description: event?.description || 'Event details on BeatHub'
	};
}

export default async function EventDetailsPage({ params }: PageProps) {
	const event = await getEventById(params.id);
	const success = cookies().get('eventCreated');

	return (
		<main className="flex-1 py-12">
			<div>
				<h1>Event Details Page: Event - {params.id}</h1>
				{success && <p className="font-semibold text-green-400">New Event Created!</p>}
			</div>
			<pre>{JSON.stringify(event, null, 2)}</pre>
		</main>
	);
}
